[workspace]
members = [
    "arcdps",
    "arcdps_codegen",
    "arcdps_example_plugin",
    "evtc",
    "evtc_dump",
    "evtc_parse",
]
resolver = "2"


[workspace.dependencies]
windows = { version = "0.59.0" }
