[package]
name = "arcdps"
version = "0.10.0"
authors = ["Zerthox", "Greaka"]
edition = "2021"
description = "Rust bindings for ArcDPS plugins"
repository = "https://github.com/zerthox/arcdps-bindings"
categories = ["api-bindings"]
keywords = ["arcdps", "guild-wars-2", "ffi", "addon", "framework"]
license = "MIT"

[dependencies]
arcdps_codegen = { path = "../arcdps_codegen" }
arcdps_evtc = { path = "../arcdps_evtc" }
arcdps-imgui = { version = "0.8.0", features = ["tables-api"] }
chrono = "0.4.24"
log = { version = "0.4.17", features = ["std"], optional = true }
num_enum = "0.6.0"
serde = { version = "1.0.160", features = ["derive"], optional = true }
strum = { version = "0.24.1", features = ["derive"], optional = true }

[dependencies.windows]
version = "0.48.0"
features = [
    "System",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Direct3D11",
]

[features]
default = []
extras = ["arcdps_codegen/extras"]
serde = ["dep:serde", "arcdps_evtc/serde", "chrono/serde"]
strum = ["dep:strum", "arcdps_evtc/strum"]
