(function() {var implementors = {
"arcdps_imgui":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"arcdps_imgui/drag_drop/struct.PayloadIsWrongType.html\" title=\"struct arcdps_imgui::drag_drop::PayloadIsWrongType\">PayloadIsWrongType</a>"]],
"arcdps_parse":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"arcdps_parse/enum.ParseError.html\" title=\"enum arcdps_parse::ParseError\">ParseError</a>"]],
"chrono":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"chrono/format/struct.ParseError.html\" title=\"struct chrono::format::ParseError\">ParseError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"chrono/enum.RoundingError.html\" title=\"enum chrono::RoundingError\">RoundingError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"chrono/struct.ParseWeekdayError.html\" title=\"struct chrono::ParseWeekdayError\">ParseWeekdayError</a>"]],
"log":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"log/struct.SetLoggerError.html\" title=\"struct log::SetLoggerError\">SetLoggerError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"log/struct.ParseLevelError.html\" title=\"struct log::ParseLevelError\">ParseLevelError</a>"]],
"num_enum":[["impl&lt;Enum:&nbsp;<a class=\"trait\" href=\"num_enum/trait.TryFromPrimitive.html\" title=\"trait num_enum::TryFromPrimitive\">TryFromPrimitive</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"num_enum/struct.TryFromPrimitiveError.html\" title=\"struct num_enum::TryFromPrimitiveError\">TryFromPrimitiveError</a>&lt;Enum&gt;"]],
"proc_macro2":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"proc_macro2/struct.LexError.html\" title=\"struct proc_macro2::LexError\">LexError</a>"]],
"proc_macro_crate":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"proc_macro_crate/enum.Error.html\" title=\"enum proc_macro_crate::Error\">Error</a>"]],
"serde":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"serde/de/value/struct.Error.html\" title=\"struct serde::de::value::Error\">Error</a>"]],
"strum":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"strum/enum.ParseError.html\" title=\"enum strum::ParseError\">ParseError</a>"]],
"time":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"time/struct.OutOfRangeError.html\" title=\"struct time::OutOfRangeError\">OutOfRangeError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"time/enum.ParseError.html\" title=\"enum time::ParseError\">ParseError</a>"]],
"toml_datetime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"toml_datetime/struct.DatetimeParseError.html\" title=\"struct toml_datetime::DatetimeParseError\">DatetimeParseError</a>"]],
"toml_edit":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"toml_edit/struct.TomlError.html\" title=\"struct toml_edit::TomlError\">TomlError</a>"]],
"windows":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"windows/core/struct.Error.html\" title=\"struct windows::core::Error\">Error</a>"]],
"winnow":[["impl&lt;I:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + 'static&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"winnow/error/struct.Error.html\" title=\"struct winnow::error::Error\">Error</a>&lt;I&gt;"],["impl&lt;I:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + 'static&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"winnow/error/struct.VerboseError.html\" title=\"struct winnow::error::VerboseError\">VerboseError</a>&lt;I&gt;"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()