name: Check

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**/src/**"
      - Cargo.toml
  pull_request:
    paths:
      - "**/src/**"
      - Cargo.toml

jobs:
  check:
    name: Check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --all-features
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
  clippy:
    name: Clippy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy --all-features -- --deny warnings
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt -- --check
