name: Release

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  release:
    name: Build (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
          - name: win
            os: windows-latest
          - name: macos
            os: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release --package evtc_dump
      - uses: actions/upload-artifact@v3
        with:
          name: evtc_dump_${{ matrix.name }}
          path: |
              target/release/evtc_dump
              target/release/evtc_dump.exe
      - uses: vimtor/action-zip@v1.1
        with:
          files: target/release/evtc_dump target/release/evtc_dump.exe
          dest: evtc_dump_${{ matrix.name }}.zip
      - uses: softprops/action-gh-release@v1
        continue-on-error: true
        with:
          files: evtc_dump_${{ matrix.name }}.zip
